sudo: false
language: generic
os: osx
before_install:
  - brew update
  - brew install python
  - virtualenv venv -p python
  - source venv/bin/activate
  - pip install -r requirements.txt
script:
  - python setup.py nosetests
  - coverage report --show-missing
after_success:
  coveralls
